[book]
authors = ["veltzer"]
language = "en"
src = "src"
title = "RSEar - Train Your Ears"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rsear"
edit-url-template = "https://github.com/veltzer/rsear/edit/master/docs/{path}"
